arcoiris=("azul","verde","rojo","amarillo")
print(arcoiris)
print("-longitud arcoiris-")
print(len(arcoiris))
animales=("pantera",20,"estatura",1.7)
print(animales)
print(" \n elementos de la tupla")
print(animales[1])
rateros = ("juan", "ana", "pedro")
y = list(rateros)
y[1] = "polancoas"
x = tuple(y)
print(x)
print("agregando elementos")
nanimal=("boby","chetos")
y = list(nanimal)
print(y)
y.append("tontolin")
otrat = tuple(y)
print(otrat)

print("\n uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)

